[build-system]
requires = ["setuptools>=40.8.0", "wheel>=0.29.0"]
build-backend = "setuptools.build_meta"

[tool.autoflake]
recursive = true
check_diff = true
exclude = "*_pb2.py"

[tool.isort]
line_length = 80
profile = "google"
skip_glob = ["*_pb2.py"]
