# Copyright 2016 Google Inc. All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Utilities for integration testing OpenHTF examples."""

from typing import Any
import unittest


class ExampleTestBase(unittest.TestCase):
  """Base class for integration testing OpenHTF examples."""

  def get_phase_by_name(
      self, json_data: dict[str, Any], phase_name: str
  ) -> dict[str, Any]:
    """Finds a phase by its name in a test output JSON.

    Args:
      json_data: The JSON data as loaded from the output file, generated by the
        default JSON output callback.
      phase_name: The name of the phase to find.

    Returns:
      The phase dictionary if found.

    Raises:
      AssertionError (via test_case.fail()): If the phase is not found
        or json_data does not have the expected "phases" key.
    """
    if "phases" not in json_data:
      self.fail("JSON data does not contain 'phases' key.")
    for p in json_data["phases"]:
      if p["name"] == phase_name:
        return p
    self.fail(f"Phase '{phase_name}' not found in output.")
