"""Utilities for integration testing OpenHTF examples."""

import os
from typing import Any
import unittest


class ExampleTestBase(unittest.TestCase):
  """Base class for integration testing OpenHTF examples."""

  def setUp(self):
    super().setUp()
    self.output_file = None

  def tearDown(self):
    super().tearDown()
    if self.output_file and os.path.exists(self.output_file):
      os.remove(self.output_file)

  def get_phase_by_name(
      self, json_data: dict[str, Any], phase_name: str
  ) -> dict[str, Any]:
    """Finds a phase by its name in a test output JSON.

    Args:
      json_data: The JSON data as loaded from the output file, generated by the
        default JSON output callback.
      phase_name: The name of the phase to find.

    Returns:
      The phase dictionary if found.

    Raises:
      AssertionError (via test_case.fail()): If the phase is not found
        or json_data does not have the expected "phases" key.
    """
    if "phases" not in json_data:
      self.fail("JSON data does not contain 'phases' key.")
    for p in json_data["phases"]:
      if p["name"] == phase_name:
        return p
    self.fail(f"Phase '{phase_name}' not found in output.")
